version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs....working......
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - echo $Name > uri.txt
      - sed -i "s|MONGODB_URI=.*|MONGODB_URI='$Name'|g" .env
  build:
    commands:
      - echo building...
      - npm install
       
  post_build:
    commands:
      - chmod +x Appstop.sh Appstart.sh  
       
artifacts:
  files:
    - "**/*"
